services:
  pg-db:
    image: postgres:16.4
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # - ./docker-data/db:/var/lib/postgresql/data
    networks:
      - app-network

  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:3000
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@pg-db:${DB_PORT}/${DB_NAME}
    networks:
      - app-network
    depends_on:
      - pg-db

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
